---
- name: deploy haproxy
  hosts: frontends
  gather_facts: false 
  become: true

  vars:
    frontend_packages:
      - httpie
      - haproxy

  tasks:

    - name: Install frontend packages
      package:
        name: "{{ frontend_packages }}"
        state: present

    - name: enable haproxy
      service:
        name: haproxy
        state: started

    - name: configure haproxy
      template:
        src: ../templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: restart_haproxy

  handlers:

    - name: restart_haproxy
      service:
        name: haproxy
        state: restarted
