---
- name: Downgrade chocolatey to fix ansible bug
  win_chocolatey:       
    name: chocolatey       
    state: downgrade       
    version: 0.10.11

- name: Install Windows package
  win_chocolatey:
    name: "{{ package_name }}"
    params: "{{ parameters }}"
    state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Start windows service
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Add win_firewall_rule
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes
