---
# tasks file for roles/win_ad_user
- name: Create windows domain group
  win_domain_group:
    name: "{{ item.group_name }}"
    scope: "{{ item.group_scope }}"
    state: present
  loop: "{{ user_info }}"

- name: Create AD User
  win_domain_user:
   name: "{{ item.name }}"
   firstname: "{{item.firstname }}"
   surname: "{{ item.surname }}"
   password: "{{ item.password }}"
   groups: "{{ item.group_name }}"
   state: present
   email: '"{{ item.name }}"@ad1.2c18.example.opentlc.com'
  loop: "{{ user_info }}"
