- name: Create server instances
  os_server:
    cloud: ospcloud
    name: "{{ item.instance_name }}"
    image: rhel-guest
    meta: "group={{ item.group }},deployment_name={{ item.deployment }}"
    flavor: m2.small
    security_groups: "{{ item.security_group_name }}"
    key_name: ansible_ssh
    wait: yes
    nics:
    - net-name: int_network
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
      cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  loop: "{{ openstack_instances }}"      
  register: r_instances

- name: output register r_instances  
  debug:
    verbosity: 2  
    msg: 
      - "Register results are {{ item.changed}}"
      - "Register results are {{ item._ansible_item_result }}"
      - "Register results are {{ item.item.instance_name }}"
      - "VM State results are {{ item.server.vm_state }}"
  loop: "{{ r_instances.results }}"


- name: Add floating IP to instances
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: "{{ item.item.instance_name }}"
    network: ext_network
    wait: true
    timeout: 180
  loop: "{{ r_instances.results }}"
  register: r_floating_ips

- name: debug task to output register  
  debug:
    msg: " instance ip register is {{ r_floating_ips.results }}"
    
- name: print out the value of r_floating_ips
  template:
    src: floating_ip.j2
    dest: floating_ip.json
  delegate_to: localhost

- name: Show public IP
  debug: 
    verbosity: 2
    msg: "Floating IP is {{ item.item }}"
    #`msg: "Floating IP is {{ item.item.floating_ips.floating_ip_address }}"
  loop: "{{ r_floating_ips.results }}"
  
- name: pause
  pause:

- name: Wait for servers by name to be available
  wait_for:
    #host: "{{ item.item.instance_name  }}"
    #    host: "{{ item.item.floating_ip.floating_ip_address }}"
    #host: "{{ item.item.openstack.interface_ip }}"
    host: "{{ item.item.openstack.public_v4 }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600
  loop: "{{ r_floating_ips.results }}"
  #loop: "{{ r_instances.results }}"
  delegate_to: "{{ inventory_hostname }}"

#- name: Wait for servers to be available
#  wait_for:
#    host: "{{ item.item.floating_ips.floating_ip_address }}"
#    port: 22
#    search_regex: OpenSSH
#    timeout: 600
#  loop: "{{ r_floating_ips.results }}"  
#  delegate_to: "{{ inventory_hostname }}"
