---
- name: Install haproxy
  package:
    name: haproxy
    state: present

- name: Enable haproxy at boot
  service:
    name: haproxy
    enabled: yes

- name: Configure haproxy to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: Start haproxy
  service:
    name: haproxy
    state: restarted
